version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: 890942158228.dkr.ecr.ap-northeast-1.amazonaws.com/tomi-todo-front:latest
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    platform: linux/amd64
    networks:
      - app-network

  frontend-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: 890942158228.dkr.ecr.ap-northeast-1.amazonaws.com/tomi-todo-front-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
    platform: linux/amd64
    tty: true
    stdin_open: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
