version: '3.8'

services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/src/app
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    networks:
      - app-network
    # depends_on:
    #   - backend

  frontend-nginx:
    image: nginx:latest
    container_name: "frontend_nginx"
    ports:
      - '8081:80'
    volumes:
      - .:/var/www
      - ./nginx/frontend.conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    external: true
