services:
  backend:
    build: .
    tty: true
    volumes:
      - .:/var/www
    # ports:
    #   - '8000:8000'
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - mysql

  backend-nginx:
    image: nginx:latest
    container_name: "backend_nginx"
    ports:
      - '8888:80'
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - mysql
    networks:
      - app-network
    env_file:
      - ./.env
networks:
  app-network:
    external: true
