FROM nginx:latest

WORKDIR /etc/nginx


COPY default.conf /etc/nginx/conf.d/default.conf

# Nginx のエラーログを詳細に出す
# RUN echo 'error_log /var/log/nginx/error.log debug;' >> /etc/nginx/nginx.conf

EXPOSE 80


